apiVersion: v1
kind: Service
metadata:
  name: transaction-management
spec:
  selector:
    app: transaction-management
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort